var FrameworkError = {
  AUTHENTICATE_INVALID_TYPE: 1000,
  
  AUTHENTICATE_NO_USER: 1010,
  AUTHENTICATE_WRONG_PASSWORD: 1011,
    
  MODULE_NOT_INITIALIZE: 1100
};

exports.FrameworkError = FrameworkError;